# Once Release PR merges
# Tag as release
# Release
# Publish

name: Tag and Publish

on:
  pull_request:
    types:
      - closed  # Only trigger when a PR is merged
    branches:
      - master  # Only trigger when merged into master

jobs:
  tag_and_publish:
    if: startsWith(github.event.pull_request.head.ref, 'release-v')  # Only run for release PRs
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Get Version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Tag the Release
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git tag "v${{ env.VERSION }}"
          git push origin "refs/tags/v${{ env.VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: true
          prerelease: false
          generate_release_notes: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      # Set up Docker Buildx for multi-architecture builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image for multiple architectures
      - name: Build and Push Docker Image
        run: |
          VERSION=${{ env.VERSION }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --file Dockerfile \
            --tag rhinosecuritylabs/cloudgoat:$VERSION \
            --tag rhinosecuritylabs/cloudgoat:latest \
            --push .
